---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: obsidian
description: Alma Linux Atomic LTS

base-image: quay.io/almalinuxorg/almalinux-bootc
image-version: 10

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    group-install:
      with-optional: true
      packages:
        - kde-desktop-environment
    install:
      packages:
        - epel-release
        - podman
        - podman-docker

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
