# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: obsidian
description: Alma Linux Atomic LTS
base-image: quay.io/almalinuxorg/almalinux-bootc
image-version: 10

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    install:
      packages:
        - epel-release

  - type: dnf
    group-install:
      with-optional: true
      packages:
        - kde-desktop-environment

  - type: dnf
    install:
      packages:
        - podman
        - podman-docker

  - type: signing